### ISSUE TITLE
Service is not accessible when following Build and deploy to Azure Kubernetes Service with Azure Pipelines

### ISSUE THREAD

**Issue by p1johnson** [MicrosoftDocs/pipelines-javascript-docker#30]
Following the How To guide here: https://docs.microsoft.com/en-us/azure/aks/devops-pipeline?view=azure-devops&pivots=pipelines-yaml

The latest pull request #26 has changed the port that the express app listens on from 8080 to 3000, so when the Azure Pipeline creates the service in AKS the app is no longer accessible. The default service.yml file configures a service port but not a target port, so the default action is for the target port to be the same as the service port. This defaults to 80 when creating a pipeline from the template, but reading the How To guide, it is implied that this will be set to 8080, based on the instruction to 'Open a new browser tab or window and enter <IP address>:8080.'

**Comment by DaveInga** [comment]
Both the Dockerfile and server.js should listen on the same port, similar to 969c7c262d4e2877d5e363f564495848f4c9ac77

**Comment by p1johnson** [comment]
> Both the Dockerfile and server.js should listen on the same port, similar to [969c7c2](https://github.com/MicrosoftDocs/pipelines-javascript-docker/commit/969c7c262d4e2877d5e363f564495848f4c9ac77)

I've got a PR in to do just that and also to match the service port specified in the How To guide.
